# 迭代与生成器

`for-of`循环等内置语言结构会忽略状态为`done: true`的`IteratorObject`内部返回的值。所以迭代器或者生成器的即使返回 `{ done: true, value: 1 }` 对于 `for-of` 也无法取得这个 `1`

## 迭代器

可选的`return()`方法用于指定在迭代器提前关闭时执行的逻辑。

执行迭代的结构在想让迭代器知道它不想遍历到可迭代对象耗尽时，就可以“关闭”迭代器。可能的情况包括：

- `for-of`循环通过`break`、`continue`、`return`或`throw`提前退出；
- 解构操作并未消费所有值。

`return()`方法必须返回一个有效的`IteratorResult`对象。简单情况下，可以只返回`{done: true }`。因为这个返回值只会用在生成器的上下文中。

因为`return()`方法是可选的，所以并非所有迭代器都是可关闭的。要知道某个迭代器是否可关闭，可以测试这个迭代器实例的`return`属性是不是函数对象。不过，仅仅给一个不可关闭的迭代器增加这个方法并不能让它变成可关闭的。这是因为调用`return()`不会强制迭代器进入关闭状态。即便如此，`return()`方法还是会被调用。

```js
class Counter {
  constructor(limit) {
    this.limit = limit;
  }

  [Symbol.iterator]() {
    let count = 1,
      limit = this.limit;
    return {
      next() {
        const it = count < limit ? { done: false, value: count++ } : { done: true };
        console.log(it);
        return it;
      },
      return() {
        console.log("Existing Early");
        return { done: true };
      },
    };
  }
}

// 提前退出的情况

var [a, b] = new Counter(5);
// 输出（for of 提前终止也是同理）：
// { done:false, value:1}
// { done:false, value:2}
// Existing Early
```

## 生成器

- 只要是可以定义函数的地方，就可以定义生成器。 
- 箭头函数不能用来定义生成器函数。
- 生成器函数只会在初次调用`next()`方法后开始执行。
- `yield`关键字可以让生成器停止和开始执行，也是生成器最有用的地方。生成器函数在遇到`yield`关键字之前会正常执行。遇到这个关键字后，执行会停止，函数作用域的状态会被保留。停止执行的生成器函数只能通过在生成器对象上调用`next()`方法来恢复执行
- 通过`yield`关键字退出的生成器函数会处在`done: false`状态；通过`return`关键字退出的生成器函数会处于`done: true`状态
- 除了可以作为函数的中间返回语句使用，`yield`关键字还可以作为函数的中间参数使用。上一次让生成器函数暂停的`yield`关键字会接收到传给`next()`方法的第一个值。这里有个地方不太好理解——第一次调用`next()`传入的值不会被使用，因为这一次调用是为了开始执行生成器函数
- 生成器格外适合作为默认迭代器，即对象中可以声明 `*[Symbol.iterator] () { ... }`
- 可以使用星号增强 yield 的行为，让它能够**迭代一个可迭代对象，从而一次产出一个值**

```js
function * g() { 
  yield * [1, 2, 3]; // 同理，可以 yield * 一个迭代器或者生成器
}

for(let el of g()) {
  console.log(el);
}
```

- 生成器除了用有 `next()`、`return()` 之外，还拥有 `throw()` 方法。`return()`和`throw()`方法都可以用于强制生成器进入关闭状态
- 生成器的 `return()` 可以主动调用结束生成器，当调用 `return()` 后所有之后的值都变得不可取，即便生成器还未执行结束，但每次调用 `next()` 都只会得到 `{ done: true, value: undefined }` 值。
- `throw()` 方法会在暂停的时候将一个提供的错误注入到生成器对象中。如果错误未被处理，生成器就会关闭。错误处理会跳过对应的`yield`，即会跳过一个值。